on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:
    inputs:
      authorization:
        description: 'Auth code provided'
        required: true

name: CD process

permissions:
  pull-requests: write

jobs:
  terraform:
    name: "Deploy AWS and Application"
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: "default"
    steps:

      - name: process dispatch should fail if not authorized
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          echo ::add-mask::${{secrets.GH_DISPATCH_AUTH}}
          if ! [[ "$user_authorization" = "${{secrets.GH_DISPATCH_AUTH}}" ]]; then
            echo "::error::autorization code not valid"
            exit 1
          fi
        env:
          user_authorization: ${{github.event.inputs.authorization}}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.7.5

      - name: Plan when PR execute when Main
        uses: tchupp/actions-terraform-pr@v1
        with:
          apply-branch: "main"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{vars.AWS_DEFAULT_REGION}}

      - name: Terraform outputs
        if: github.ref == 'refs/heads/main'
        run: |
          echo '# Terraform Outputs' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          terraform output >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "URL: http://$(terraform output --raw  dns_name)" >> $GITHUB_STEP_SUMMARY
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{vars.AWS_DEFAULT_REGION}}
